name: CI

on:
  # push:
  #   branches: 
  #       - "main"

  workflow_dispatch:

env:
  NVCC_FLAGS: "--allow-unsupported-compiler"
  DISTUTILS_USE_SDK: 1
  FORCE_CUDA: 1
  XFORMERS_BUILD_TYPE: "Release"
  MAX_JOBS: 4

jobs:
  build:

    # defaults:
    #   run:
    #     shell: bash

    timeout-minutes: 360
    
    strategy:

      fail-fast: false

      matrix:
        os:
          - windows-2019
          - ubuntu-18.04

        python:
          - "3.10"
          - "3.8"

        config:
          - cuda-version: '11.6.2'
            commit-hash: 'e773f9dd362e'
            arch-list:  "5.0;5.2+PTX;5.3;6.0;6.1+PTX;7.0+PTX;7.5+PTX;8.0;8.6+PTX" # from https://github.com/pytorch/pytorch/blob/fe87ae692f813934d1a74d000fd1e3b546c27ae2/torch/utils/cpp_extension.py#L1740
            torch-install-command: 'torch==1.13.0+cu116 torchvision==0.14.0+cu116 --extra-index-url https://download.pytorch.org/whl/cu116'
            torch-ver: '1.13.0+cu116'
            alt: ''
            last-date: '2022-12-20'

          - cuda-version: '11.8.0'
            commit-hash: 'e773f9dd362e'
            arch-list:  "5.0;5.2+PTX;5.3;6.0;6.1+PTX;7.0+PTX;7.5+PTX;8.0;8.6+PTX" # from https://github.com/pytorch/pytorch/blob/fe87ae692f813934d1a74d000fd1e3b546c27ae2/torch/utils/cpp_extension.py#L1740
            torch-install-command: 'torch==1.13.0+cu117 torchvision==0.14.0+cu117 --extra-index-url https://download.pytorch.org/whl/cu117'
            torch-ver: '1.13.0+cu117'
            alt: ''
            last-date: '2022-12-20'

          - cuda-version: '11.8.0'
            commit-hash: 'e773f9dd362e'
            arch-list:  "5.0;5.2+PTX;5.3;6.0;6.1+PTX;7.0+PTX;7.5+PTX;8.0;8.6+PTX" # from https://github.com/pytorch/pytorch/blob/fe87ae692f813934d1a74d000fd1e3b546c27ae2/torch/utils/cpp_extension.py#L1740
            torch-install-command: 'torch==1.14.0.dev20221121+cu117 torchvision==0.15.0.dev20221121+cu117 --extra-index-url https://download.pytorch.org/whl/nightly'
            torch-ver: '1.14.0.dev20221121+cu117'
            alt: ''
            last-date: '2022-12-20'

    name: xformers-${{ matrix.config.last-date }}-Py-${{ matrix.python }}-Cuda-${{ matrix.config.cuda-version }}-PyTorch-${{ matrix.config.torch-ver }}-${{ matrix.os }}${{ matrix.config.alt }}
    
    runs-on: ${{ matrix.os }}

    steps:

      - id: Cleanup-Linux-Enviroment
        if: runner.os == 'Linux'
        uses: ZyCromerZ/slimhub_actions@main

      - uses: actions/setup-python@v4
        id: python
        with:
          python-version: ${{ matrix.python }}

      - id: msvc
        uses: ilammy/msvc-dev-cmd@release/v1 
        # with:
        #   vsversion: 2022

      # - name: (Windows) Remove link.exe
      #   if: runner.os == 'Windows'
      #   run: rm /usr/bin/link

      - id: configure-pagefile
        if: runner.os == 'Windows'
        uses: al-cheb/configure-pagefile-action@v1.3
        with:
          minimum-size: 32GB
          disk-root: "C:"

      - id: configure-swap
        if: runner.os == 'Linux'
        uses: pierotofy/set-swap-space@master
        # with:
        #   swap-size-gb: 10

      - id: prepare-build
        run: |
          git clone https://github.com/facebookresearch/xformers.git
          cd xformers
          git reset --hard ${{ matrix.config.commit-hash }}
          pip install wheel setuptools ninja --no-cache-dir
          pip install ${{ matrix.config.torch-install-command }} --prefer-binary --no-cache-dir
          pip install -r requirements.txt --prefer-binary --no-cache-dir
          pip cache purge
          git submodule update --init --recursive

      - id: winmemhack
        if: runner.os == 'Windows'
        run: (Get-Content xformers\setup.py) -replace '"4"', '"1"' | Out-File xformers\setup.py

      - id: linmemhack
        if: runner.os == 'Linux'
        run: sed -i 's/"4"/"1"/' xformers/setup.py

      - id: cuda-toolkit-win
        if: runner.os == 'Windows'
        uses: ZyCromerZ/cuda-toolkit@master
        with:
          cuda: ${{ matrix.config.cuda-version }}
          method: network
          use-github-cache: false

      - id: cuda-toolkit-linux
        if: runner.os == 'Linux'
        uses: ZyCromerZ/cuda-toolkit@master
        with:
          cuda: ${{ matrix.config.cuda-version }}
          linux-local-args: '["--toolkit"]'
          use-github-cache: false

      - id: build
        env:
          CUDA_HOME: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}
          TORCH_CUDA_ARCH_LIST: "${{ matrix.config.arch-list }}"
        run: |
          cd xformers
          python setup.py bdist_wheel

      - uses: actions/upload-artifact@v3
        with:
          name: xformers-${{ matrix.config.last-date }}-Py-${{ matrix.python }}-Cuda-${{ matrix.config.cuda-version }}-PyTorch-${{ matrix.config.torch-ver }}-${{ matrix.os }}${{ matrix.config.alt }}
          path: xformers/dist/*.whl

      - id: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "xformers/dist/*.whl"
          tag: xformers-${{ matrix.config.last-date }}-Py-${{ matrix.python }}-Cuda-${{ matrix.config.cuda-version }}-PyTorch-${{ matrix.config.torch-ver }}-${{ matrix.os }}${{ matrix.config.alt }}
          commit: ${{ github.sha }}
